version: '2'
services:
    filmmonster-app:
        image: filmmonster
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://filmmonster-postgresql:5432/filmmonster
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=filmmonster-elasticsearch:9300
        ports:
            - 8080:8080
    filmmonster-postgresql:
        extends:
            file: postgresql.yml
            service: filmmonster-postgresql
    filmmonster-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: filmmonster-elasticsearch
